// *****************************************************************************************************************
// Configuration for different microcontrollers (MCU) to ensure compatibility with the code:
// - Defines the clock speed, timers, and interrupts for each MCU.
// - Configures I/O pins for data, clocks, and switches according to the requirements.
// - Enables pull-up resistors on input pins where needed.
// - Manages external interrupts and LED outputs for system feedback.
// - Ensures the setup is compatible with various microcontroller models (e.g., ATmega328, ATtiny series, etc.)
// *****************************************************************************************************************

//******************************************************************************************************************
// Configuring the clock speed and associated registers. The formula for calculating
// the clock frequency is F_CPU / (TCCR0B |= (1<<CS00)) * (OCR0A = 159 +1) = 16000000 / (0 * (160)) = 100KHz
//******************************************************************************************************************

//******************************************************************************************************************
// Example: DDRB &= ~(1<<DDB0);  // Create a mask by shifting the bit 1 to the left by DDB0's position (bit 0), and then inverting it.
// The bitwise AND operation (&=) updates the register DDRB by clearing the DDB0 bit (setting it to 0)
// without affecting the other bits.
//
// For instance, if DDRB = b11111111 (binary value), the operation shifts the bit 1 to the left to create the mask
// (1<<DDB0) = b00000001, and then inverts it, which results in b11111110. The AND operation with DDRB clears DDB0.
//
// Before:  DDRB = b11111111  // Initial value of DDRB (all pins set as output)
// Mask:    ~(b00000001) = b11111110  // Mask generated by shifting and inverting the bit
// After:   DDRB = b11111110  // The DDB0 bit is cleared (set to 0), while other bits remain unchanged
//******************************************************************************************************************

//******************************************************************************************************************
// Example: DDRB |= (1<<DDB0);  // Create a mask by shifting the bit 1 to the left by DDB0's position (bit 0),
// and then apply a bitwise OR operation to set DDB0 to 1 (configure pin PB0 as an output).
//
// For instance, if DDRB = b11111111 (binary value), the operation shifts the bit 1 to the left to create the mask
// (1<<DDB0) = b00000001. The OR operation with DDRB sets the DDB0 bit to 1, leaving other bits unchanged.
//
// Before:  DDRB = b11111111  // Initial value of DDRB (all pins set as output)
// Mask:    (1<<DDB0) = b00000001  // Mask generated by shifting the bit 1 to the left to position DDB0
// After:   DDRB = b11111111  // The DDB0 bit is set to 1, configuring pin PB0 as an output
//******************************************************************************************************************

//******************************************************************************************************************
// Example: (PIND & (1<<PIND6));  // Create a mask by shifting the bit 1 to the left by PIND6's position (bit 6),
// and then apply a bitwise AND operation to read the state of the PIND6 pin.
// The result will be non-zero (true) if the PIND6 pin is high (1), and zero (false) if the PIND6 pin is low (0).
//
// For instance, if PIND = b10101010 (binary value), the operation shifts the bit 1 to the left to create the mask
// (1<<PIND6) = b01000000. The AND operation between PIND and the mask checks if the 6th bit is set to 1 (high).
//
// Before:  PIND = b10101010  // Initial value of PIND (register containing input pin states)
// Mask:    (1<<PIND6) = b01000000  // Mask generated by shifting the bit 1 to the left to position PIND6
// Operation: PIND & b01000000 = b00000000 // If PIND6 is low (0)
// Operation: PIND & b01000000 = b01000000 // If PIND6 is high (1)
//
//******************************************************************************************************************

//******************************************************************************************************************
// Example: EICRA |= (1<<ISC01) | (1<<ISC00);
// This operation configures the external interrupt sense control (ISC) for interrupt INT0 (External Interrupt Request 0).
// Specifically, it sets the mode of INT0 to "rising edge" trigger, meaning the interrupt will be triggered when the pin
// transitions from low to high (rising edge).
//
// EICRA (External Interrupt Control Register A) controls how external interrupts INT0 and INT1 are triggered.
// The bits ISC01 and ISC00 in this register define the trigger mode for interrupt INT0.
//
// - Setting ISC01 to 1 and ISC00 to 1 (via the OR operation) configures INT0 to trigger on the rising edge.
//
// Before:  EICRA = b00000000  // Initial value of EICRA, all interrupt sense control bits are cleared (no trigger mode set).
// Operation: EICRA |= (1<<ISC01) | (1<<ISC00)  // Set ISC01 and ISC00 to 1 for rising edge trigger.
// After:   EICRA = b00000011  // The bits ISC01 and ISC00 are now set, configuring INT0 to trigger on rising edge.
//
// This technique is commonly used to configure external interrupts to trigger based on specific events like a rising
// or falling edge on the external interrupt pin (INT0 or INT1).
//******************************************************************************************************************

//******************************************************************************************************************
// Example: EICRA = (EICRA & ~(1<<ISC00)) | (1<<ISC01);
// This operation configures the external interrupt sense control (ISC) for interrupt INT0 (External Interrupt Request 0).
// Specifically, it sets INT0 to trigger on a "falling edge" (when the signal transitions from high to low).
//
// The bits ISC01 and ISC00 in the EICRA register define how the external interrupt INT0 is triggered. The operation
// clears the bit ISC00 while setting ISC01 to 1, configuring INT0 to trigger when the pin transitions from high to low,
// i.e., on the falling edge.
//
// EICRA (External Interrupt Control Register A) controls how external interrupts INT0 and INT1 are triggered.
// - ISC01 = 1, ISC00 = 0 configures INT0 to trigger on falling edge (high to low transition).
//
// Before:  EICRA = b00000011  // Initial value with ISC01 = 1 and ISC00 = 1 (rising edge trigger for INT0)
// Operation: EICRA & ~(1<<ISC00) clears ISC00 bit (sets it to 0) while keeping ISC01 at 1. Then OR operation with (1<<ISC01) ensures ISC01 stays 1.
// After:   EICRA = b00000010  // The bit ISC00 is now cleared, configuring INT0 to trigger on the falling edge.
//
// This technique is used to configure the interrupt to trigger on the falling edge (transition from high to low),
// without changing the state of other control bits in the EICRA register.
//******************************************************************************************************************

#pragma once

#if defined(__AVR_ATmega328__)   || defined(__AVR_ATmega328A__)  || \
    defined(__AVR_ATmega328P__)  || defined(__AVR_ATmega328PA__) || \
    defined(__AVR_ATmega328PB__) || defined(__AVR_ATmega168__)   || \
    defined(__AVR_ATmega168A__)  || defined(__AVR_ATmega168P__)  || \
    defined(__AVR_ATmega168PA__) || defined(__AVR_ATmega168PB__) || \
    defined(__AVR_ATmega128A__)  || defined(__AVR_ATmega128PB__)

#define IS_328_168_FAMILY
  /*------------------------------------------------------------------------------------------------
  * FUNCTION    : optimizePeripherals()
  * 
  * DESCRIPTION : 
  *    Minimizes power consumption and internal noise by disabling unused hardware modules.
  *    Performs a hard shutdown of peripherals to reduce current leakage and CPU jitter.
  * 
  *    1. ANALOG SHUTDOWN: Disables ADC and Analog Comparator to prevent parasitic drain.
  *    2. BUFFER DISABLE: Disconnects digital input buffers on analog pins (A0-A5).
  *    3. CLOCK GATING (PRR): Shuts down clocks to TWI, SPI, and all Timers (0, 1, 2).
  *    4. UART MAINTENANCE: Keeps PRUSART0 active to allow Serial communication.
  ------------------------------------------------------------------------------------------------*/
  void OptimizePeripherals(void) __attribute__((naked, section(".init3")));

  void OptimizePeripherals(void) {
    
  }

#ifndef F_CPU
#define F_CPU 133000000L  // RP2040 typically runs at 133MHz
#endif

#include <Arduino.h>
#include <stdint.h>
#include <stdbool.h>
#include <Adafruit_NeoPixel.h>


// Global interrupt control settings
#define GLOBAL_INTERRUPT_ENABLE     interrupts()
#define GLOBAL_INTERRUPT_DISABLE    noInterrupts()

// Define pin numbers for the RP2040 - adjust these to match your wiring
#define PIN_DATA                    2    // GP2
#define PIN_WFCK                    3    // GP3
#define PIN_SQCK                    4    // GP4  
#define PIN_SUBQ                    5    // GP5

// Main pin configuration for input and output
#define PIN_DATA_INPUT              pinMode(PIN_DATA, INPUT)
#define PIN_WFCK_INPUT              pinMode(PIN_WFCK, INPUT)
#define PIN_SQCK_INPUT              pinMode(PIN_SQCK, INPUT)
#define PIN_SUBQ_INPUT              pinMode(PIN_SUBQ, INPUT)
                            
// Output configuration
#define PIN_DATA_OUTPUT             pinMode(PIN_DATA, OUTPUT)
#define PIN_WFCK_OUTPUT             pinMode(PIN_WFCK, OUTPUT)
           
// Setting pins high
#define PIN_DATA_SET                digitalWrite(PIN_DATA, HIGH)
             
// Setting pins low
#define PIN_DATA_CLEAR              digitalWrite(PIN_DATA, LOW)
#define PIN_WFCK_CLEAR              digitalWrite(PIN_WFCK, LOW)
                         
// Reading pin states
#define PIN_SQCK_READ               digitalRead(PIN_SQCK)
#define PIN_SUBQ_READ               digitalRead(PIN_SUBQ)
#define PIN_WFCK_READ               digitalRead(PIN_WFCK)

// Timer interrupt handling
#define TIMER_INTERRUPT_ENABLE      // Handled in code via attachInterrupt
#define TIMER_INTERRUPT_DISABLE     // Handled in code via detachInterrupt
#define TIMER_TIFR_CLEAR            // Not applicable for RP2040

  #if defined(SCPH_102)       || \
      defined(SCPH_100)       || \
      defined(SCPH_7000_7500_9000) || \
      defined(SCPH_7000)      || \
      defined(SCPH_3500_5000_5500) || \
      defined(SCPH_3000)      || \
      defined(SCPH_1000)

      #define PIN_AX                      6    // GP6
      #define PIN_DX                      8    // GP8


      // Define input pins for the BIOS patch
      #define PIN_AX_INPUT                pinMode(PIN_AX, INPUT)
      #define PIN_DX_INPUT                pinMode(PIN_DX, INPUT)

      // Define output pins for the BIOS patch
      #define PIN_DX_OUTPUT               pinMode(PIN_DX, OUTPUT)

      // Set pins high
      #define PIN_DX_SET                  digitalWrite(PIN_DX, HIGH)

      // Set pins low
      #define PIN_DX_CLEAR                digitalWrite(PIN_DX, LOW)

      // Read pins
      #define PIN_AX_READ                 digitalRead(PIN_AX)

      // External interrupt configuration - handled differently on RP2040
      #define PIN_AX_INTERRUPT_ENABLE     // Handled in code via attachInterrupt
      #define PIN_AX_INTERRUPT_DISABLE    // Handled in code via detachInterrupt

      // Interrupt trigger modes
      #define PIN_AX_INTERRUPT_RISING     // Handled in code via attachInterrupt(PIN_AX, ax_isr, RISING)
      #define PIN_AX_INTERRUPT_FALLING    // Handled in code via attachInterrupt(PIN_AX, ax_isr, FALLING)

      // Secondary Address line (AY) for multi-stage patching (INT1)
      #define PIN_AX_INTERRUPT_VECTOR     // Not applicable for RP2040

        #if defined(SCPH_3000) || \
            defined(SCPH_1000)

          #define PIN_AY                      7    // GP7
          #define PIN_AY_INPUT                pinMode(PIN_AY, INPUT)
          #define PIN_AY_READ                 digitalRead(PIN_AY)
          #define PIN_AY_INTERRUPT_ENABLE     // Handled in code via attachInterrupt
          #define PIN_AY_INTERRUPT_DISABLE    // Handled in code via detachInterrupt
          #define PIN_AY_INTERRUPT_RISING     // Handled in code via attachInterrupt(PIN_AY, ay_isr, RISING)
          #define PIN_AY_INTERRUPT_FALLING    // Handled in code via attachInterrupt(PIN_AY, ay_isr, FALLING)
          #define PIN_AY_INTERRUPT_FALLING    // Handled in code via attachInterrupt(PIN_AY, ay_isr, FALLING)
          #define PIN_AY_INTERRUPT_VECTOR     // Not applicable for RP2040
        #endif  

      // Hardware Bypass Switch (On-the-fly deactivation)
      #ifdef PATCH_SWITCHE
        #define PIN_SWITCH                  9    // GP9
        #define PIN_SWITCH_INPUT            pinMode(PIN_SWITCH, INPUT_PULLUP)
        #define PIN_SWITCH_SET              // Not applicable, using INPUT_PULLUP
        #define PIN_SWITCH_READ             digitalRead(PIN_SWITCH)
      #endif
    #endif  
// The RP2040 Zero uses a NeoPixel (WS2812B) as an onboard LED
Adafruit_NeoPixel pixels(1, PIN_NEOPIXEL, NEO_GRB + NEO_KHZ800); // Create a NeoPixel object

// Arduino-style delay functions for RP2040
#define _delay_us(us) delayMicroseconds(us)
#define _delay_ms(ms) delay(ms)

// Variables for tracking time in RP2040 implementation
unsigned long timer_start_micros = 0;
unsigned long timer_start_millis = 0;
bool timer_running = false;
#endif



