// *****************************************************************************************************************
// Configuration for different microcontrollers (MCU) to ensure compatibility with the code:
// - Defines the clock speed, timers, and interrupts for each MCU.
// - Configures I/O pins for data, clocks, and switches according to the requirements.
// - Enables pull-up resistors on input pins where needed.
// - Manages external interrupts and LED outputs for system feedback.
// - Ensures the setup is compatible with various microcontroller models (e.g., ATmega328, ATtiny series, etc.)
// *****************************************************************************************************************

//******************************************************************************************************************
// Configuring the clock speed and associated registers. The formula for calculating
// the clock frequency is F_CPU / (TCCR0B |= (1<<CS00)) * (OCR0A = 159 +1) = 16000000 / (0 * (160)) = 100KHz
//******************************************************************************************************************

//******************************************************************************************************************
// Example: DDRB &= ~(1<<DDB0);  // Create a mask by shifting the bit 1 to the left by DDB0's position (bit 0), and then inverting it.
// The bitwise AND operation (&=) updates the register DDRB by clearing the DDB0 bit (setting it to 0)
// without affecting the other bits.
//
// For instance, if DDRB = b11111111 (binary value), the operation shifts the bit 1 to the left to create the mask
// (1<<DDB0) = b00000001, and then inverts it, which results in b11111110. The AND operation with DDRB clears DDB0.
//
// Before:  DDRB = b11111111  // Initial value of DDRB (all pins set as output)
// Mask:    ~(b00000001) = b11111110  // Mask generated by shifting and inverting the bit
// After:   DDRB = b11111110  // The DDB0 bit is cleared (set to 0), while other bits remain unchanged
//******************************************************************************************************************

//******************************************************************************************************************
// Example: DDRB |= (1<<DDB0);  // Create a mask by shifting the bit 1 to the left by DDB0's position (bit 0),
// and then apply a bitwise OR operation to set DDB0 to 1 (configure pin PB0 as an output).
//
// For instance, if DDRB = b11111111 (binary value), the operation shifts the bit 1 to the left to create the mask
// (1<<DDB0) = b00000001. The OR operation with DDRB sets the DDB0 bit to 1, leaving other bits unchanged.
//
// Before:  DDRB = b11111111  // Initial value of DDRB (all pins set as output)
// Mask:    (1<<DDB0) = b00000001  // Mask generated by shifting the bit 1 to the left to position DDB0
// After:   DDRB = b11111111  // The DDB0 bit is set to 1, configuring pin PB0 as an output
//******************************************************************************************************************

//******************************************************************************************************************
// Example: (PIND & (1<<PIND6));  // Create a mask by shifting the bit 1 to the left by PIND6's position (bit 6),
// and then apply a bitwise AND operation to read the state of the PIND6 pin.
// The result will be non-zero (true) if the PIND6 pin is high (1), and zero (false) if the PIND6 pin is low (0).
//
// For instance, if PIND = b10101010 (binary value), the operation shifts the bit 1 to the left to create the mask
// (1<<PIND6) = b01000000. The AND operation between PIND and the mask checks if the 6th bit is set to 1 (high).
//
// Before:  PIND = b10101010  // Initial value of PIND (register containing input pin states)
// Mask:    (1<<PIND6) = b01000000  // Mask generated by shifting the bit 1 to the left to position PIND6
// Operation: PIND & b01000000 = b00000000 // If PIND6 is low (0)
// Operation: PIND & b01000000 = b01000000 // If PIND6 is high (1)
//
//******************************************************************************************************************

//******************************************************************************************************************
// Example: EICRA |= (1<<ISC01) | (1<<ISC00);
// This operation configures the external interrupt sense control (ISC) for interrupt INT0 (External Interrupt Request 0).
// Specifically, it sets the mode of INT0 to "rising edge" trigger, meaning the interrupt will be triggered when the pin
// transitions from low to high (rising edge).
//
// EICRA (External Interrupt Control Register A) controls how external interrupts INT0 and INT1 are triggered.
// The bits ISC01 and ISC00 in this register define the trigger mode for interrupt INT0.
//
// - Setting ISC01 to 1 and ISC00 to 1 (via the OR operation) configures INT0 to trigger on the rising edge.
//
// Before:  EICRA = b00000000  // Initial value of EICRA, all interrupt sense control bits are cleared (no trigger mode set).
// Operation: EICRA |= (1<<ISC01) | (1<<ISC00)  // Set ISC01 and ISC00 to 1 for rising edge trigger.
// After:   EICRA = b00000011  // The bits ISC01 and ISC00 are now set, configuring INT0 to trigger on rising edge.
//
// This technique is commonly used to configure external interrupts to trigger based on specific events like a rising
// or falling edge on the external interrupt pin (INT0 or INT1).
//******************************************************************************************************************

//******************************************************************************************************************
// Example: EICRA = (EICRA & ~(1<<ISC00)) | (1<<ISC01);
// This operation configures the external interrupt sense control (ISC) for interrupt INT0 (External Interrupt Request 0).
// Specifically, it sets INT0 to trigger on a "falling edge" (when the signal transitions from high to low).
//
// The bits ISC01 and ISC00 in the EICRA register define how the external interrupt INT0 is triggered. The operation
// clears the bit ISC00 while setting ISC01 to 1, configuring INT0 to trigger when the pin transitions from high to low,
// i.e., on the falling edge.
//
// EICRA (External Interrupt Control Register A) controls how external interrupts INT0 and INT1 are triggered.
// - ISC01 = 1, ISC00 = 0 configures INT0 to trigger on falling edge (high to low transition).
//
// Before:  EICRA = b00000011  // Initial value with ISC01 = 1 and ISC00 = 1 (rising edge trigger for INT0)
// Operation: EICRA & ~(1<<ISC00) clears ISC00 bit (sets it to 0) while keeping ISC01 at 1. Then OR operation with (1<<ISC01) ensures ISC01 stays 1.
// After:   EICRA = b00000010  // The bit ISC00 is now cleared, configuring INT0 to trigger on the falling edge.
//
// This technique is used to configure the interrupt to trigger on the falling edge (transition from high to low),
// without changing the state of other control bits in the EICRA register.
//******************************************************************************************************************

#pragma once

#if defined(__AVR_ATmega328__)   || defined(__AVR_ATmega328A__)  || \
    defined(__AVR_ATmega328P__)  || defined(__AVR_ATmega328PA__) || \
    defined(__AVR_ATmega328PB__) || defined(__AVR_ATmega168__)   || \
    defined(__AVR_ATmega168A__)  || defined(__AVR_ATmega168P__)  || \
    defined(__AVR_ATmega168PA__) || defined(__AVR_ATmega168PB__) || \
    defined(__AVR_ATmega128A__)  || defined(__AVR_ATmega128PB__)

#define IS_328_168_FAMILY
  /*------------------------------------------------------------------------------------------------
  * FUNCTION    : optimizePeripherals()
  * 
  * DESCRIPTION : 
  *    Minimizes power consumption and internal noise by disabling unused hardware modules.
  *    Performs a hard shutdown of peripherals to reduce current leakage and CPU jitter.
  * 
  *    1. ANALOG SHUTDOWN: Disables ADC and Analog Comparator to prevent parasitic drain.
  *    2. BUFFER DISABLE: Disconnects digital input buffers on analog pins (A0-A5).
  *    3. CLOCK GATING (PRR): Shuts down clocks to TWI, SPI, and all Timers (0, 1, 2).
  *    4. UART MAINTENANCE: Keeps PRUSART0 active to allow Serial communication.
  ------------------------------------------------------------------------------------------------*/
  void OptimizePeripherals(void) __attribute__((naked, section(".init3")));

  void OptimizePeripherals(void) {
    
    // Watchdog Timer Shutdown (Prevent Boot-Loop) 
    MCUSR = 0;
    WDTCSR |= (1 << WDCE) | (1 << WDE);
    WDTCSR = 0x00;


    // Disable Interrupts during setup
    cli();

    // Analog Modules Shutdown (Critical for Power)
    ADCSRA = 0;             // Disable ADC
    ACSR   |= (1 << ACD);   // Disable Analog Comparator

    DIDR0 = 0xFF; // Pins A0 to A7
    #if defined(__AVR_ATmega128PB__)
      DIDR2 = 0xFF;
    #endif

    // GPIO Strategy (Unused pins to Pull-up)
    // PORTx = 0xFF (Pull-ups) | DDRx = 0x00 (Inputs)
    PORTC |= 0xFF;
    #if defined(__AVR_ATmega328PB__) || defined(__AVR_ATmega128PB__)
      PORTE |= 0x0F; // Le Port E existe sur la série PB (PE0 à PE3)
    #endif
    // Power Reduction Register (PRR)
    // We KEEP PRUSART0 (UART) and shut down EVERYTHING else.
    // _delay_ms() will still work (it's cycle-based, not timer-based).

    #if defined(__AVR_ATmega328PB__)
      PRR0  = (1 << PRTWI0) | // I2C Off
              (1 << PRSPI0) | // SPI Off
              (1 << PRTIM0) | // Timer 0 Off
              (1 << PRTIM1) | // Timer 1 Off
              (1 << PRTIM2) | // Timer 2 Off
              (1 << PRADC);   // ADC Clock Off

      PRR1  = (1 << PRTWI1) | // TWI 1 Off
              (1 << PRSPI1) | // SPI 1 Off
              (1 << PRTIM3) | // Timer 3 Off
              (1 << PRTIM4);  // Timer 4 Off

    #elif defined(__AVR_ATmega128PB__)
      PRR0  = (1 << PRTWI0) | // I2C Off
              (1 << PRSPI0) | // SPI Off
              (1 << PRTIM0) | // Timer 0 Off
              (1 << PRTIM1) | // Timer 1 Off
              (1 << PRTIM2) | // Timer 2 Off
              (1 << PRADC);   // ADC Clock Off

      PRR1  = (1 << PRTWI1) | // TWI 1 Off
              (1 << PRSPI1) | // SPI 1 Off
              (1 << PRTIM3) | // Timer 3 Off
              (1 << PRTIM4);  // Timer 4 Off

      PRR2  = (1 << PRTIM5);  // Timer 5 Off 

    #else
      PRR   = (1 << PRTWI)  | // I2C Off
              (1 << PRSPI)  | // SPI Off
              (1 << PRTIM0) | // Timer 0 Off
              (1 << PRTIM1) | // Timer 1 Off
              (1 << PRTIM2) | // Timer 2 Off
              (1 << PRADC);   // ADC Clock Off
    #endif


    // Double Security for Timer 0
    TCCR0B = 0; TIMSK0 = 0; // Timer 0
    TCCR1B = 0; TIMSK1 = 0; // Timer 1
    TCCR2B = 0; TIMSK2 = 0; // Timer 2
    #if defined(TCCR3B)
      TCCR3B = 0; TIMSK3 = 0; // Timer 3 (série PB)
      TCCR4B = 0; TIMSK4 = 0; // Timer 4 (série PB)
    #endif
  }

  #include <stdint.h>
  #include <stdbool.h>
  #include <avr/io.h>
  #include <avr/interrupt.h>
  #include <avr/sfr_defs.h>
  #include <util/delay.h>



  // Main pin configuration

  // Define the main pins as inputs
  #define PIN_DATA_INPUT DDRB &= ~(1 << DDB0)  // Set DDRB register to configure PINB0 as input
  #define PIN_WFCK_INPUT DDRB &= ~(1 << DDB1)  // Set DDRB register to configure PINB1 as input
  #define PIN_SQCK_INPUT DDRD &= ~(1 << DDD6)  // Set DDRD register to configure PINB6 as input
  #define PIN_SUBQ_INPUT DDRD &= ~(1 << DDD7)  // Set DDRD register to configure PINB7 as input

  // Configure lines as outputs (for injection/override)
  #define PIN_DATA_OUTPUT DDRB |= (1 << DDB0)  // Set DDRB register to configure PINB0 as output
  #define PIN_WFCK_OUTPUT DDRB |= (1 << DDB1)  // Set DDRB register to configure PINB1 as output

  // Bus line state control (Set High / Clear Low)
  #define PIN_DATA_SET PORTB |= (1 << PB0)  // Set PORTB register to make PINB0 high (enable pull-up))
  #define PIN_DATA_CLEAR PORTB &= ~(1 << PB0)  // Set PORTB register to make PINB0 low
  #define PIN_WFCK_CLEAR PORTB &= ~(1 << PB1)  // Set PORTB register to make PINB1 low

  // Direct Register Reading (High-speed polling)
  #define PIN_SQCK_READ (!!(PIND & (1 << PIND6)))  // Check if the value of PIND6 is high (1)
  #define PIN_SUBQ_READ (!!(PIND & (1 << PIND7)))  // Check if the value of PIND7 is high (1)
  #define PIN_WFCK_READ (!!(PINB & (1 << PINB1)))  // Check if the value of PINB1 is high (1)

  // --- Status Indication (LED) ---
  #ifdef LED_RUN
    #define PIN_LED_OUTPUT DDRB |= (1 << DDB5)  // Configure PINB5 as output (for LED)
    #define PIN_LED_ON    PORTB |= (1 << PB5)  // Set PINB5 high (turn on LED)
    #define PIN_LED_OFF   PORTB &= ~(1 << PB5)  // Set PINB5 low (turn off LED)
  #endif

  // --- BIOS Patching Configuration ---
  #if defined(SCPH_102)       || \
      defined(SCPH_100)       || \
      defined(SCPH_7000_7500_9000) || \
      defined(SCPH_7000)      || \
      defined(SCPH_3500_5000_5500) || \
      defined(SCPH_3000)      || \
      defined(SCPH_1000)

    // Address (AX) and Data (DX) lines for BIOS override
    #define PIN_DX_INPUT DDRD &= ~(1 << DDD4)
    #define PIN_DX_OUTPUT DDRD |= (1 << DDD4)
    #define PIN_DX_SET PORTD |= (1 << PD4)
    #define PIN_DX_CLEAR PORTD &= ~(1 << PD4)

    #define PIN_AX_INPUT DDRD &= ~(1 << DDD2)
    #define WAIT_AX_RISING    (!(PIND & (1 << PIND2)))  // Wait for pulse start (Blocking until Rising Edge)
    #define WAIT_AX_FALLING   (PIND & (1 << PIND2))     // Wait for pulse end (Blocking until Falling Edge)
    #define PIN_AX_READ   (!!(PIND & (1 << PIND2))) 

    // Hardware Interrupt (INT0) for AX pulse counting
    #define PIN_AX_INTERRUPT_ENABLE     EIMSK  |=  (1<<INT0)      // Enable external interrupt on INT0 (PINB3)
    #define PIN_AX_INTERRUPT_DISABLE    EIMSK  &= ~(1<<INT0)      // Disable external interrupt on INT0
    #define PIN_AX_INTERRUPT_RISING     EICRA  |=  (1<<ISC01)|(1<<ISC00)                  // Configure INT0 for rising edge trigger
    #define PIN_AX_INTERRUPT_VECTOR     INT0_vect               // Interrupt vector for INT0 (external interrupt)
    #define PIN_AX_INTERRUPT_CLEAR      EIFR |= (1 << INTF0)  

    // Secondary Address line (AY) for multi-stage patching (INT1)
    #if defined(SCPH_3000) || \
        defined(SCPH_1000)
      #define PIN_AY_INPUT       DDRD &= ~(1 << DDD3)  // Set DDRD register to configure PIND3 as input
      #define WAIT_AY_RISING     (!(PIND & (1 << PIND3))) 
      #define WAIT_AY_FALLING    (PIND & (1 << PIND3))
      
      #define PIN_AY_INTERRUPT_ENABLE     EIMSK  |=  (1<<INT1)      // Enable external interrupt on INT1 (PINB3)
      #define PIN_AY_INTERRUPT_DISABLE    EIMSK  &= ~(1<<INT1)      // Disable external interrupt on INT1
      #define PIN_AY_INTERRUPT_RISING     EICRA  |=  (1<<ISC11)|(1<<ISC10)                  // Configure INT1 for rising edge trigger
      #define PIN_AY_INTERRUPT_FALLING    EICRA = (EICRA & ~((1 << ISC11) | (1 << ISC10))) | (1 << ISC11) // Configure INT1 for falling edge trigger
      #define PIN_AY_INTERRUPT_VECTOR     INT1_vect              // Interrupt vector for INT1 (external interrupt)
      #define PIN_AY_INTERRUPT_CLEAR    EIFR |= (1 << INTF1)
    #endif

     // Hardware Bypass Switch (On-the-fly deactivation)
    #ifdef PATCH_SWITCHE
      #define PIN_SWITCH_INPUT DDRD &= ~(1 << DDD5)  // Configure PIND5 as input for switch
      #define PIN_SWITCH_SET   PORTD |= (1 << PD5)     // Set PIND5 high (enable pull-up)
      #define PIN_SWITCH_READ (!!(PIND & (1 << PIND5)))  // Read the state of PIND5 (switch input)
    #endif

  #endif

  // #if defined(DEBUG_SERIAL_MONITOR)
  //   #define DEBUG_PRINT(x)     Serial.print(x)
  //   #define DEBUG_PRINTHEX(x)  Serial.print(x, HEX)
  //   #define DEBUG_PRINTLN(x)   Serial.println(x)
  //   #define DEBUG_FLUSH        Serial.flush()
  // #endif

#endif



